### ISSUE TITLE
Date is ahead by 1 day when showing events 

### ISSUE THREAD

**Issue by vishalxl** [Giszmo/nostr.info#1]
<img width="1280" alt="2022-08-29 (6)" src="https://user-images.githubusercontent.com/64505169/187099962-451d0d5f-031d-4af6-a793-4a74c2377fad.png">

Its 29th today, right now where I am, 5 am, but the UI is showing 30th Aug, 5 am, 1 day ahead.

**Comment by Giszmo** [comment]
Fixed.
