### ISSUE TITLE
CORS error with https://relay.nostr.info

### ISSUE THREAD

**Issue by SamSamskies** [Giszmo/nostr.info#19]
![Screenshot 2023-02-17 at 4 32 35 PM](https://user-images.githubusercontent.com/3655410/219808128-0540c658-ec3e-4372-a5c4-05d2cd3ae41a.png)

![Screenshot 2023-02-17 at 4 33 03 PM](https://user-images.githubusercontent.com/3655410/219808184-302328be-2103-4ea3-aacb-5a4e094e5dcd.png)

**Comment by Giszmo** [comment]
I don't know how to fix or reproduce that. In my config there is only one header added with the capitalized writing.

**Comment by Giszmo** [comment]
this should be fixed. Switching from one relay implementation to another had added the header in two different places.
