### ISSUE TITLE
nostr.info/relays is not showing kind 42 events or all the events

### ISSUE THREAD

**Issue by vishalxl** [Giszmo/nostr.info#5]
On doing dropdown on all events, nothing is shown or updated. 

But if you select individual kinds like 1, 7 etc, then those kinds are shown. 

But kind 42 is not shown, so I suppose problem is with kind 42. This was first observed 1-2 hours go from this post.

<img width="1280" alt="2022-11-08 (2)" src="https://user-images.githubusercontent.com/64505169/200533663-b6186dd0-b7d9-410b-8a50-f1da5f18df16.png">

Dev console screenshot shows whats seen when drop down is at all events.
<img width="1280" alt="2022-11-08 (4)" src="https://user-images.githubusercontent.com/64505169/200571091-0d0ba249-d19e-46ab-b0f2-ac9925a3f10a.png">

**Comment by vishalxl** [comment]
Its working well now. I guess whatever the malformed events were, now aren't processed.

**Comment by Giszmo** [comment]
It's not handling well the exception thrown when deserializing invalid JSON I guess. PRs welcome. Sorry for late reply. Might also be fixed already.

**Comment by Giszmo** [comment]
I think I fixed that one at some point.
